### PR TITLE
when a translation is missing log error in log-file

### PR DESCRIPTION
**Pull request by sanaullah**

### CODE REVIEW

**Comment by bdw429s** [comment]
Are all the files here?  All I see are some changes in a view.

**Comment by sanaullah** [comment]
that is just a little display formatting. core changes are in modules folder

**Comment by bdw429s** [comment]
Look at the "Files Changed" tab.  I don't see any other changes.  Am I missing something?

**Comment by sanaullah** [comment]
Seems like github display issue, emailed you the changed cfc file for comparison

**Comment by bdw429s** [comment]
Hmm, weird.  I see now that the change is there on line 149, but not showing up.  I wonder if the line breaks are differnt.

**Comment by bdw429s** [comment]
Should this log only be thrown if there is not a default?  Also, perhaps this should be an info message instead of error?

**Comment by sanaullah** [comment]
In production Apps most of users only trap error level messaging

**Comment by bdw429s** [comment]
Yes, I know which is why I'm reticent to log these as errors.  This could have the potential to fill up error logs with thousands of errors and the user might not even care about the data.  My thought was that if they want to see it, they can lower their logging settings to something like info.  I guess at the end of the day, they can create a custom logging category, but I just assumed it would be something turned off by default.

**Pull request closed without merging**
