### PR TITLE
Implements the ability to specify a custom resource service

### PR DESCRIPTION
**Pull request by jclausen**
Trying again :)

This adds functionality to specify a custom resource service to allow for customized i18n implementations. (e.g. - Database storage).

When the plugin architecture was removed from CB4, previous implementations which used the extensions/plugins conventions to override the i18n implementation became incompatible with this module.

This module will allow for upgrade capability to CB4 for those CB3 plugin extensions by creating a new setting of customResourceService which will overrides the resourceService@cbi18n mapping.

### CODE REVIEW

**Comment by jclausen** [comment]
@lmajano: Build has been updated to latest snapshot of Lucee 5.  With the fix for LDEV-820, I have re-enabled the Travis tests for L5 and all checks are passing.

**Comment by lmajano** [comment]
@jclausen This is great. Have a question for you. I see us using the docker approach of lucee 5 for all our modules and core libraries. however, is there a way we can store all these config files somehere in our artifacts file instead of storing them in each repo?

Imagine the scenario we need to update the config. Better in one place than 20 modules.

**Comment by jclausen** [comment]
@lmajano: I thought about that.  The core Lucee config files you probably could, but the Dockerfiles may need to be changed repo-by-repo, depending on the functionality.  CBORM and ContentBox, for example need a MySQL container deployed too (I've CBORM set up already and it's building fine locally, but I've got to tweak why it's failing on Travis:  https://travis-ci.org/jclausen/cbox-cborm/builds/126393432 ).  Couchbase modules would need a container for that, etc, etc.

For modules that don't have dependencies any dependencies, though, you could probably clone the cbox-module-template, copy those configs, and use them for the build.

**Comment by jclausen** [comment]
Actually, what you could do is add a repo of only Dockerfiles and libs and then pull them in to each build.  You could then just pull that repo down to `workbench/docker`.  You'd just need a unique `docker-compose.yml` in each project root which would tell the build which docker file to point to:

https://github.com/jclausen/cbox-cborm/blob/development/docker-compose.yml

**Comment by jclausen** [comment]
This has now been updated to use the docker-buildfiles repo and is now testing ACF11 as well.

**Pull request merged**
